# Generated by Django 6.0.7 on 2026-08-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workinghours",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                    ("saturday", "Saturday"),
                    ("sunday", "Sunday"),
                ],
                max_length=10,
            ),
        ),
    ]
